apiVersion: v1
kind: Secret
metadata:
  name: aws-secret
type: Opaque
data:
  aws_access_key_id: QUtJQTZEQ1pUTU9LSlI0QTNJT08=
  aws_secret_access_key: b2VLNmJQRTcxTjZuT3ZZS3JXT3loWS9lZHhsRUtFanRXTEJUZjVPMA==
