apiVersion: v1
kind: Service
metadata:
  name: udagram-frontend-app
  labels:
    app: udagram-frontend-app
spec:
  ports:
    - name: "8100"
      port: 80
      targetPort: 80
      protocol: TCP
  selector:
    service: udagram-frontend-app
