apiVersion: apps/v1
kind: Deployment
metadata:
  name: reverseproxy
  labels:
    app: reverseproxy
spec:
  replicas: 1
  selector:
    matchLabels:
      app: reverseproxy
  template:
    metadata:
      labels:
        app: reverseproxy
    spec:
      containers:
        - image: kinggeorge1/reverseproxy:v10
          name: reverseproxy
          imagePullPolicy: Always
          ports:
            - containerPort: 80
          resources:
            limits:
              cpu: 500m
            requests:
              cpu: 200m
          # envFrom:
          #   - configMapRef:
          #       name: env-configmap
          #   - secretRef:
          #       name: env-secret

      restartPolicy: Always
